package com.courzelo.lms.entities.reclamation;

import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import jakarta.validation.constraints.Size;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Document
@NoArgsConstructor
public class TrelloBoard {

    @Id
    private String id;

    @Size(max = 255)
    private String name;

    @Size(max = 255)
    private String idListToDo;

    @Size(max = 255)
    private String idListDoing;

    @Size(max = 255)
    private String idListDone;

    @DBRef
    private ReclamationType type;

    // Getters and setters are generated by Lombok's @Data annotation
}
